### ISSUE TITLE
API design problem - mapJsonToSelf is package protected

### ISSUE THREAD

**Issue by ahtremblay** [phaxio/phaxio-java#7]
The phaxio callback passes a JsonObject of the Fax object. mapJsonToSelf would be the perfect function to use to parse the json into a unusable JAVA object. However mapJsonToSelf is protected and cannot be used outside the package. There does not seem to be an alternative to get a java Fax object from the callback json, other then calling Fax.status with the id provide from the callback. However, this counts as an extra call to the server.

Possible fix:
create a Fax constructor taking a JsonObject as a parameter, and calling mapJsonToSelf during initialization.

**Comment by jnankin** [comment]
Hi Alexandre.  

Yes, we will implement suggestion and add a constructor.  Should be out shortly.

Thanks,
Josh
